### ISSUE TITLE
 RuntimeError: Expected object of scalar type Long but got scalar type Int for argument #3 'index'

### ISSUE THREAD

**Issue by haofengsiji** [floodsung/LearningToCompare_FSL#30]
I have already tried my best to solve this problem.
But I failed, can anyone give me some suggestions?

```
(py36) E:\GitHub\LearningToCompare_FSL>F:/Anaconda3/envs/py36/python.exe e:/GitHub/LearningToCompare_FSL/omniglot/omniglot_train_few_shot.py
init data folders
init neural networks
Training...
F:\Anaconda3\envs\py36\lib\site-packages\torch\nn\functional.py:1386: UserWarning: nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.
  warnings.warn("nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.")
Traceback (most recent call last):
  File "e:/GitHub/LearningToCompare_FSL/omniglot/omniglot_train_few_shot.py", line 264, in <module>
    main()
  File "e:/GitHub/LearningToCompare_FSL/omniglot/omniglot_train_few_shot.py", line 188, in main
    one_hot_labels = Variable(torch.zeros(BATCH_NUM_PER_CLASS*CLASS_NUM, CLASS_NUM).scatter_(1, batch_labels.view(-1,1), 1).cuda(GPU))
RuntimeError: Expected object of scalar type Long but got scalar type Int for argument #3 'index'
```

**Comment by yitianhoulai** [comment]
The 3rd argument index should be batch_labels.view(-1,1) and you just need to change it to 

_one_hot_labels = Variable(torch.zeros(BATCH_NUM_PER_CLASS*CLASS_NUM, CLASS_NUM).scatter_(1, batch_labels.view(-1,1).long(), 1).cuda(GPU))_

**Comment by haofengsiji** [comment]
py27 may also solve this problem, but still, thanks
